# From:
  # https://www.docker.com/blog/docker-github-actions/
  # https://github.com/metcalfc/docker-action-examples

name: Publish images to Docker hub

on:
  push:
    branches: main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
